apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ldap-oauth-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-example
        spec:
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: RoleBinding 
                metadata:
                  
          remediationAction: inform
          severity: high
  remediationAction: enforce

