apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: enforce-oauth-ldap-binding
  namespace: acm-policies 
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: global-acm-policies
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: ldap-oauth-policy
